# Generated by Django 4.2.16 on 2026-06-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatrefile',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
