# Generated by Django 5.0.14 on 2026-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_theatrefile_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatrefile",
            name="still_image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
