# Generated by Django 5.0.14 on 2026-06-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_theatrefile_still_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatrefile',
            name='still_image_compatible',
            field=models.BooleanField(default=True),
        ),
    ]
