# Generated by Django 5.0.14 on 2026-10-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0004_theatrefile_still_image_compatible"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheatreFileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="examples.theatrefile"),
                ),
            ],
        ),
    ]
