# Generated by Django 5.0.14 on 2026-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_crc", models.CharField(blank=True, max_length=255, null=True)),
                ("symbol_type", models.CharField(blank=True, max_length=24, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "qualified_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("line_start", models.IntegerField()),
                (
                    "kind",
                    models.CharField(blank=True, default="", max_length=32, null=True),
                ),
                ("is_exported", models.BooleanField(default=False)),
                ("is_static", models.BooleanField(default=False)),
                ("signature", models.TextField(blank=True, default="", null=True)),
                ("params_text", models.TextField(blank=True, default="", null=True)),
                ("comments_text", models.TextField(blank=True, default="", null=True)),
                ("search_text", models.TextField(blank=True, default="", null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="docs_source_name_ca83f2_idx"),
                    models.Index(
                        fields=["qualified_name"], name="docs_source_qualifi_3f278e_idx"
                    ),
                    models.Index(
                        fields=["symbol_type", "name"],
                        name="docs_source_symbol__3d7e2e_idx",
                    ),
                    models.Index(
                        fields=["is_exported"], name="docs_source_is_expo_e91a74_idx"
                    ),
                    models.Index(
                        fields=["line_start"], name="docs_source_line_st_ea1228_idx"
                    ),
                ],
            },
        ),
    ]
