# Generated by Django 4.2.16 on 2026-06-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_searchweightrule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchweightrule',
            new_name='docs_search_target_747ffe_idx',
            old_name='docs_searchw_target_136040_idx',
        ),
        migrations.RenameIndex(
            model_name='searchweightrule',
            new_name='docs_search_enabled_7142ec_idx',
            old_name='docs_searchw_enabled_983d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcereference',
            new_name='docs_source_ranking_726dc7_idx',
            old_name='docs_source_rankin_4a4136_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcereference',
            new_name='docs_source_rank_we_8f631d_idx',
            old_name='docs_source_rank_w_7fcb8d_idx',
        ),
    ]
