bind = "unix:/run/gunicorn/polypointjs.sock"
workers = 3
user = "site"
group = "www-data"
umask = 0o007
timeout = 30
accesslog = "/var/log/gunicorn/polypointjs_com_access.log"
errorlog = "/var/log/gunicorn/polypointjs_com_error.log"
loglevel = "info"
chdir = "/home/site/apps/polypoint/site/beta"
# module = "polypoint_beta.wsgi:application"