###
#
# The Asset yaml can _add_ to the config.
# Where the primary config in a destination can point to this space
# and append this content to the config.
# Then the config loads work, using this asset as additions for the tasks.
#
# Consider this the fine-grain addon to the primary pointer.
#
# Read more in the default-deployment.yaml
# Default capture name: "pocket-deployment.yaml"
#
###


# the source path to pull from
# git_url: 'git@github.com:Strangemother/polypoint.git'

# Apt installs
# apt:
#   update: false
#   install:
#     - nginx